// All 17 cars with real images, in catalog order (by savings %)
const CARS = [
  { id:1, slug:'mercedes-g580-eq', img:'images/car-mercedes-g580-eq.jpg',
    eyebrow:'EV · 2025 · MERCEDES', name:'Mercedes-Benz G580 with EQ',
    year:2025, fuel:'Electric',
    specs:{ accel:'4.7s', hp:'579hp', engine:'EV', torque:'1164Nm', range:'473km', drive:'AWD' },
    ourPrice:656000, dealerPrice:1700000,
    features:['Quad-motor AWD','116 kWh','PVC heated seats','Burmester 3D','PreSafe','MBUX Hyperscreen'] },
  { id:2, slug:'lucid-air-pure', img:'images/car-lucid-air-pure.jpg',
    eyebrow:'EV · 2025 · LUCID', name:'Lucid Air Pure',
    year:2025, fuel:'Electric',
    specs:{ accel:'4.5s', hp:'430hp', engine:'EV', torque:'650Nm', range:'660km', drive:'RWD' },
    ourPrice:376000, dealerPrice:800000,
    features:['Glass canopy roof','21-speaker audio','DreamDrive Pro','29.06-min charge','Pirelli tires','Heated seats'] },
  { id:3, slug:'tesla-cybertruck-awd', img:'images/car-tesla-cybertruck-awd.jpg',
    eyebrow:'EV · 2025 · TESLA', name:'Tesla Cybertruck AWD',
    year:2025, fuel:'Electric',
    specs:{ accel:'4.3s', hp:'600hp', engine:'EV', torque:'10000Nm', range:'547km', drive:'AWD' },
    ourPrice:429000, dealerPrice:700000,
    features:['Steel exoskeleton','Full Self Driving','Vault storage','Adaptive air','Tonneau cover','Bed power outlet'] },
  { id:4, slug:'mercedes-g63-amg', img:'images/car-mercedes-g63-amg.jpg',
    eyebrow:'V8 · 2025 · MERCEDES', name:'Mercedes-AMG G63',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'3.4s', hp:'577hp', engine:'V8', torque:'850Nm', mpg:'14mpg', drive:'AWD' },
    ourPrice:1180000, dealerPrice:2100000,
    features:['4.0L V8 Biturbo','AMG Performance 4MATIC+','Burmester 3D','Heated/cooled seats','Night Package','Adaptive damping'] },
  { id:5, slug:'mercedes-gls-450d', img:'images/car-mercedes-gls-450d.jpg',
    eyebrow:'I6 DIESEL · 2025 · MERCEDES', name:'Mercedes-Benz GLS 450d',
    year:2025, fuel:'Diesel',
    specs:{ accel:'6.1s', hp:'367hp', engine:'I6d', torque:'750Nm', mpg:'24mpg', drive:'4MATIC' },
    ourPrice:574000, dealerPrice:1050000,
    features:['7 seats','E-Active Body Control','Air suspension','Panoramic roof','Massage seats','MBUX'] },
  { id:6, slug:'tesla-model-x-lr', img:'images/car-tesla-model-x-lr.jpg',
    eyebrow:'EV · 2025 · TESLA', name:'Tesla Model X Long Range',
    year:2025, fuel:'Electric',
    specs:{ accel:'3.8s', hp:'670hp', engine:'EV', torque:'659Nm', range:'560km', drive:'AWD' },
    ourPrice:429000, dealerPrice:730000,
    features:['Falcon doors','Tri-zone climate','Yoke or wheel','Premium audio','22" wheels','Full Self Driving'] },
  { id:7, slug:'chevy-tahoe-high-country', img:'images/car-chevy-tahoe-high-country.jpg',
    eyebrow:'V8 · 2025 · CHEVROLET', name:'Chevrolet Tahoe High Country',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'6.7s', hp:'420hp', engine:'V8', torque:'623Nm', mpg:'18mpg', drive:'4WD' },
    ourPrice:405000, dealerPrice:780000,
    features:['8 seats','6.2L V8','Magnetic Ride Control','Air suspension','Super Cruise','Bose Premium'] },
  { id:8, slug:'mercedes-gle-450d', img:'images/car-mercedes-gle-450d.jpg',
    eyebrow:'I6 DIESEL · 2025 · MERCEDES', name:'Mercedes-Benz GLE 450d',
    year:2025, fuel:'Diesel',
    specs:{ accel:'6.0s', hp:'367hp', engine:'I6d', torque:'750Nm', mpg:'27mpg', drive:'4MATIC' },
    ourPrice:465000, dealerPrice:785000,
    features:['EQ Boost','Air Body Control','12.3" display','Burmester','Park Pilot','Off-road package'] },
  { id:9, slug:'bmw-x7', img:'images/car-bmw-x7-xdrive40i.jpg',
    eyebrow:'I6 · 2025 · BMW', name:'BMW X7 xDrive40i',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'5.6s', hp:'375hp', engine:'I6', torque:'520Nm', mpg:'22mpg', drive:'xDrive' },
    ourPrice:543000, dealerPrice:900000,
    features:['7 seats','48V mild hybrid','Sky Lounge roof','Bowers & Wilkins','Driving Assistant Pro','M Sport Pkg'] },
  { id:10, slug:'mercedes-s580e', img:'images/car-mercedes-s580e.jpg',
    eyebrow:'PHEV · 2025 · MERCEDES', name:'Mercedes-Benz S580e 4MATIC',
    year:2025, fuel:'Plug-in Hybrid',
    specs:{ accel:'5.1s', hp:'510hp', engine:'PHEV', torque:'750Nm', range:'120km', drive:'4MATIC' },
    ourPrice:736000, dealerPrice:1050000,
    features:['Plug-in hybrid','Rear-wheel steering','Active Body Control','Burmester High-End','MBUX Hyperscreen','Executive seats'] },
  { id:11, slug:'mercedes-g500', img:'images/car-mercedes-g500.jpg',
    eyebrow:'V8 · 2025 · MERCEDES', name:'Mercedes-Benz G500',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'5.6s', hp:'416hp', engine:'V8', torque:'610Nm', mpg:'15mpg', drive:'4MATIC' },
    ourPrice:1000000, dealerPrice:1450000,
    features:['4.0L V8','Three locking diffs','Adaptive damping','Burmester','Distronic','360 camera'] },
  { id:12, slug:'ford-bronco-raptor', img:'images/car-ford-bronco-raptor.jpg',
    eyebrow:'V6 EB · 2025 · FORD', name:'Ford Bronco Raptor',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'5.3s', hp:'418hp', engine:'V6', torque:'596Nm', mpg:'15mpg', drive:'4WD' },
    ourPrice:464000, dealerPrice:805000,
    features:['HOSS 4.0 suspension','Fox shocks','37" tires','Trail Turn Assist','Lockable diffs','SYNC 4'] },
  { id:13, slug:'rivian-r1s', img:'images/car-rivian-r1s.jpg',
    eyebrow:'EV · 2025 · RIVIAN', name:'Rivian R1S Dual Motor',
    year:2025, fuel:'Electric',
    specs:{ accel:'4.5s', hp:'533hp', engine:'EV', torque:'813Nm', range:'515km', drive:'AWD' },
    ourPrice:408000, dealerPrice:550000,
    features:['7 seats','Air suspension','Tank Turn','Off-road modes','Camp mode','Glass roof'] },
  { id:14, slug:'ford-f150-raptor', img:'images/car-ford-f150-raptor.jpg',
    eyebrow:'V6 EB · 2025 · FORD', name:'Ford F-150 Raptor',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'5.6s', hp:'450hp', engine:'V6', torque:'691Nm', mpg:'16mpg', drive:'4WD' },
    ourPrice:388000, dealerPrice:680000,
    features:['Fox Live Valve','37" off-road','Trail 1-Pedal Drive','B&O sound','12" touchscreen','PowerBoost'] },
  { id:15, slug:'bmw-x5', img:'images/car-bmw-x5.jpg',
    eyebrow:'I6 · 2025 · BMW', name:'BMW X5 xDrive40i',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'5.4s', hp:'375hp', engine:'I6', torque:'520Nm', mpg:'25mpg', drive:'xDrive' },
    ourPrice:435000, dealerPrice:686000,
    features:['48V mild hybrid','Adaptive M susp','Live Cockpit','Harman Kardon','Parking Assistant','M Sport'] },
  { id:16, slug:'mustang-gt', img:'images/car-mustang-gt-v8.jpg',
    eyebrow:'V8 · 2025 · FORD', name:'Ford Mustang GT 5.0',
    year:2025, fuel:'Gasoline',
    specs:{ accel:'4.2s', hp:'480hp', engine:'V8', torque:'563Nm', mpg:'18mpg', drive:'RWD' },
    ourPrice:251000, dealerPrice:425000,
    features:['Coyote 5.0L V8','MagneRide','Active exhaust','Recaro seats','13.2" display','Brembo brakes'] },
  { id:17, slug:'kia-ev9', img:'images/car-kia-ev9.jpg',
    eyebrow:'EV · 2025 · KIA', name:'Kia EV9 GT-Line',
    year:2025, fuel:'Electric',
    specs:{ accel:'5.3s', hp:'379hp', engine:'EV', torque:'700Nm', range:'430km', drive:'AWD' },
    ourPrice:297000, dealerPrice:429000,
    features:['7 seats','100 kWh','Highway Driving Assist 2','Meridian audio','350kW fast charge','V2L power'] }
];

// Format helpers
const fmt = n => new Intl.NumberFormat('he-IL').format(n);
const calcSave = c => c.dealerPrice - c.ourPrice;
const calcPct = c => Math.round((calcSave(c) / c.dealerPrice) * 100);
