// AutoImports — 20 cars with full Cars.com-style data
// Gallery uses real photos from images/ and images/gallery/
// Price comparison: dealer (יבואן רשמי) vs. AutoImports (ours)

const FX = { usdIls: 2.93, shippingUsd: 2000, customsIls: 2000, discountUsd: 3000, servicePct: 0.05, depositIls: 500, vat: 0.18 };

const CARS = [
  {
    id: 'g63',
    name: 'Mercedes-AMG G63',
    nameHe: 'מרצדס G63 AMG',
    eyebrow: 'V8 · 2025 · MERCEDES-AMG',
    brand: 'Mercedes-AMG',
    year: 2025,
    fuel: 'בנזין',
    engine: '4.0L V8 ביטורבו',
    hp: 577, nm: 850, accel: 4.5, topSpeed: 240,
    transmission: '9G-TRONIC אוטומטי',
    drive: '4MATIC AWD מלא',
    mpg: '13.5 ק"מ/ליטר',
    seats: 5, doors: 5,
    length: 4866, width: 1984, height: 1969, weight: 2560,
    dealerPrice: 2100000, ourPrice: 1180000,
    image: 'images/car-mercedes-g63-amg.jpg',
    gallery: [
      'images/car-mercedes-g63-amg.jpg',
      'images/gallery/g63-interior.jpg',
      'images/gallery/g63-carbon.jpg',
      'images/gallery/g63-showroom.jpg',
      'images/gallery/mercedes-g63-amg-g63-3.jpg',
      'images/gallery/mercedes-g63-amg-g63-4.jpg'
    ],
    features: ['מערכת MBUX 12.3"', 'גלגלי AMG 22"', 'תיבת תאוצה ביציאת מפעל', 'מערכת אקטיבית AMG Active Ride', 'עור נאפה Exclusive', 'בורגונדי גג נפתח'],
    history: 'יבוא ישיר מארה"ב · 0 ק"מ · יד ראשונה · אחריות יצרן 4 שנים'
  },
  {
    id: 'gls450d',
    name: 'Mercedes GLS 450d',
    nameHe: 'מרצדס GLS 450d',
    eyebrow: 'DIESEL · 2025 · MERCEDES',
    brand: 'Mercedes-Benz',
    year: 2025, fuel: 'דיזל',
    engine: '3.0L I6 דיזל + EQ Boost',
    hp: 367, nm: 750, accel: 6.1, topSpeed: 250,
    transmission: '9G-TRONIC אוטומטי', drive: '4MATIC AWD',
    mpg: '11.8 ק"מ/ליטר',
    seats: 7, doors: 5,
    length: 5207, width: 1956, height: 1823, weight: 2570,
    dealerPrice: 1040000, ourPrice: 574000,
    image: 'images/car-mercedes-gls-450d.jpg',
    gallery: ['images/car-mercedes-gls-450d.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-showroom.jpg', 'images/gallery/g63-dashboard.jpg'],
    features: ['מסך MBUX היפר 12.3" כפול', '7 מושבים', 'מערכת AIRMATIC', 'גג זכוכית פנורמי', 'Burmester סראונד', 'תאורת אווירה 64 צבעים'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות מלאה'
  },
  {
    id: 'g580eq',
    name: 'Mercedes G580 EQ',
    nameHe: 'מרצדס G580 EQ',
    eyebrow: 'EV · 2025 · MERCEDES',
    brand: 'Mercedes-Benz EQ', year: 2025, fuel: 'חשמלי',
    engine: '4 מנועים חשמליים', hp: 587, nm: 1164, accel: 4.7, topSpeed: 180,
    transmission: 'אוטומט יחס יחיד', drive: 'AWD חשמלי כפול',
    mpg: '473 ק"מ טווח · WLTP',
    seats: 5, doors: 5,
    length: 4877, width: 1984, height: 1986, weight: 3085,
    dealerPrice: 1680000, ourPrice: 656000,
    image: 'images/car-mercedes-g580-eq.jpg',
    gallery: ['images/car-mercedes-g580-eq.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-carbon.jpg', 'images/gallery/g63-dashboard.jpg'],
    features: ['G-TURN סיבוב במקום', 'G-STEERING הגה חכם', 'סוללה 116kWh', 'טעינה DC 200kW', 'מצב Offroad חשמלי', 'מצלמות 360°'],
    history: 'יבוא ראשון בארץ · 0 ק"מ · אחריות סוללה 8 שנים'
  },
  {
    id: 'lucid-air',
    name: 'Lucid Air Pure',
    nameHe: 'לוסיד אייר פיור',
    eyebrow: 'EV · 2025 · LUCID',
    brand: 'Lucid Motors', year: 2025, fuel: 'חשמלי',
    engine: 'מנוע חשמלי אחורי', hp: 430, nm: 596, accel: 4.5, topSpeed: 245,
    transmission: 'אוטומט יחיד', drive: 'RWD',
    mpg: '660 ק"מ טווח · EPA',
    seats: 5, doors: 4,
    length: 4975, width: 1939, height: 1410, weight: 2240,
    dealerPrice: 800000, ourPrice: 376000,
    image: 'images/car-lucid-air-pure.jpg',
    gallery: [
      'images/car-lucid-air-pure.jpg',
      'images/gallery/lucid-air-pure-1.jpg',
      'images/gallery/lucid-air-pure-2.jpg',
      'images/gallery/lucid-air-pure-3.jpg',
      'images/gallery/lucid-air-pure-4.jpg',
      'images/gallery/lucid-air-pure-5.jpg'
    ],
    features: ['Glass Cockpit 34"', 'DreamDrive Pro', 'סוללה 88kWh', 'טעינה 300kW', 'הגה Yoke אופציה', 'מערכת קול 21 רמקולים'],
    history: 'יבוא ייחודי · 0 ק"מ · אחריות יצרן מלאה'
  },
  {
    id: 'g500',
    name: 'Mercedes G500',
    nameHe: 'מרצדס G500',
    eyebrow: 'V8 · 2025 · MERCEDES',
    brand: 'Mercedes-Benz', year: 2025, fuel: 'בנזין',
    engine: '4.0L V8 ביטורבו', hp: 449, nm: 560, accel: 5.4, topSpeed: 210,
    transmission: '9G-TRONIC', drive: '4MATIC AWD',
    mpg: '12.0 ק"מ/ליטר',
    seats: 5, doors: 5, length: 4866, width: 1984, height: 1969, weight: 2520,
    dealerPrice: 1450000, ourPrice: 1000000,
    image: 'images/car-mercedes-g500.jpg',
    gallery: ['images/car-mercedes-g500.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-side.jpg', 'images/gallery/g63-showroom.jpg'],
    features: ['G-Manufaktur עיצוב אישי', '3 נעילות דיפרנציאל', 'גלגלים 20"', 'מצלמות 360°', 'מסך MBUX 12.3"', 'מתלים AGILITY CONTROL'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות יצרן'
  },
  {
    id: 'tahoe',
    name: 'Chevy Tahoe High Country',
    nameHe: 'שברולט טאהו היי-קאנטרי',
    eyebrow: 'V8 · 2025 · CHEVROLET',
    brand: 'Chevrolet', year: 2025, fuel: 'בנזין',
    engine: '6.2L V8', hp: 420, nm: 624, accel: 6.0, topSpeed: 180,
    transmission: '10-Speed Auto', drive: '4WD',
    mpg: '8.5 ק"מ/ליטר',
    seats: 8, doors: 5, length: 5354, width: 2057, height: 1928, weight: 2580,
    dealerPrice: 700000, ourPrice: 405000,
    image: 'images/car-chevy-tahoe-high-country.jpg',
    gallery: ['images/car-chevy-tahoe-high-country.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-showroom.jpg'],
    features: ['8 מושבי קפטן', 'Super Cruise נהיגה אוטו', 'מסך 17.7"', 'Bose Premium 10 רמקולים', 'גרירה 3,856 ק"ג', 'מתלי אוויר'],
    history: 'יבוא ישיר ארה"ב · 0 ק"מ'
  },
  {
    id: 'bmw-x7',
    name: 'BMW X7 xDrive40i',
    nameHe: 'ב.מ.וו X7 40i',
    eyebrow: 'I6 · 2025 · BMW',
    brand: 'BMW', year: 2025, fuel: 'בנזין',
    engine: '3.0L I6 ביטורבו 48V', hp: 380, nm: 540, accel: 5.8, topSpeed: 250,
    transmission: '8-Speed Steptronic', drive: 'xDrive AWD',
    mpg: '10.2 ק"מ/ליטר',
    seats: 7, doors: 5, length: 5181, width: 2000, height: 1835, weight: 2435,
    dealerPrice: 950000, ourPrice: 543000,
    image: 'images/car-bmw-x7-xdrive40i.jpg',
    gallery: ['images/car-bmw-x7-xdrive40i.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-dashboard.jpg'],
    features: ['BMW Curved Display 12.3+14.9"', 'Sky Lounge גג', 'Bowers&Wilkins 1500W', 'גלגלים 22"', '7 מושבים', 'מתלים אקטיביים'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות BMW'
  },
  {
    id: 'tesla-x',
    name: 'Tesla Model X Long Range',
    nameHe: 'טסלה מודל X לונג ריינג׳',
    eyebrow: 'EV · 2025 · TESLA',
    brand: 'Tesla', year: 2025, fuel: 'חשמלי',
    engine: 'Dual Motor חשמלי', hp: 670, nm: 1020, accel: 3.9, topSpeed: 250,
    transmission: 'יחס יחיד', drive: 'AWD חשמלי',
    mpg: '560 ק"מ טווח · EPA',
    seats: 7, doors: 5, length: 5057, width: 2070, height: 1684, weight: 2459,
    dealerPrice: 800000, ourPrice: 429000,
    image: 'images/car-tesla-model-x-lr.jpg',
    gallery: ['images/car-tesla-model-x-lr.jpg', 'images/gallery/cyber-interior.jpg', 'images/gallery/cyber-screen.jpg', 'images/gallery/cyber-seat.jpg'],
    features: ['דלתות Falcon Wing', 'AutoPilot מלא', 'מסך 17" 2200×1300', '7 מושבים', 'Supercharger 250kW', 'מערכת קול 22 רמקולים'],
    history: 'יבוא ייחודי · 0 ק"מ · אחריות סוללה 8 שנים'
  },
  {
    id: 's580e',
    name: 'Mercedes S580e PHEV',
    nameHe: 'מרצדס S580e היברידי',
    eyebrow: 'PHEV · 2025 · MERCEDES',
    brand: 'Mercedes-Benz', year: 2025, fuel: 'היברידי חשמל',
    engine: '3.0L I6 + מנוע חשמלי', hp: 510, nm: 750, accel: 5.1, topSpeed: 250,
    transmission: '9G-TRONIC', drive: '4MATIC AWD',
    mpg: '113 ק"מ טווח חשמלי + 700 ק"מ סך הכל',
    seats: 5, doors: 4, length: 5290, width: 1954, height: 1503, weight: 2435,
    dealerPrice: 1200000, ourPrice: 736000,
    image: 'images/car-mercedes-s580e.jpg',
    gallery: ['images/car-mercedes-s580e.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-carbon.jpg', 'images/gallery/g63-dashboard.jpg'],
    features: ['MBUX Hyperscreen 56"', 'מושבי עיסוי אקטיביים', 'Burmester 4D', 'הגה אחורי 10°', 'תאורת אווירה 64', 'גג פנורמי חכם'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות מלאה'
  },
  {
    id: 'bronco-raptor',
    name: 'Ford Bronco Raptor',
    nameHe: 'פורד ברונקו ראפטור',
    eyebrow: 'V6 · 2025 · FORD',
    brand: 'Ford', year: 2025, fuel: 'בנזין',
    engine: '3.0L V6 EcoBoost ביטורבו', hp: 418, nm: 583, accel: 5.7, topSpeed: 180,
    transmission: '10-Speed Auto', drive: '4WD בחירני',
    mpg: '6.8 ק"מ/ליטר',
    seats: 5, doors: 4, length: 4831, width: 2199, height: 1981, weight: 2400,
    dealerPrice: 800000, ourPrice: 464000,
    image: 'images/car-ford-bronco-raptor.jpg',
    gallery: [
      'images/car-ford-bronco-raptor.jpg',
      'images/gallery/bronco-interior.jpg',
      'images/gallery/bronco-interior2.jpg',
      'images/gallery/ford-bronco-raptor-bronco-1.jpg',
      'images/gallery/ford-bronco-raptor-bronco-3.jpg',
      'images/gallery/ford-bronco-raptor-bronco-5.jpg'
    ],
    features: ['HOSS 4.0 מתלי FOX', 'גלגלים 37" שטח', 'גג נשלף', 'דלתות נשלפות', 'GOAT 7 מצבי שטח', 'SYNC 4 12" מסך'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות פורד'
  },
  {
    id: 'f150-raptor',
    name: 'Ford F-150 Raptor',
    nameHe: 'פורד F-150 ראפטור',
    eyebrow: 'V6 · 2025 · FORD',
    brand: 'Ford', year: 2025, fuel: 'בנזין',
    engine: '3.5L V6 EcoBoost ביטורבו', hp: 450, nm: 691, accel: 5.5, topSpeed: 187,
    transmission: '10-Speed Auto', drive: '4WD',
    mpg: '6.4 ק"מ/ליטר',
    seats: 5, doors: 4, length: 5897, width: 2189, height: 2027, weight: 2685,
    dealerPrice: 700000, ourPrice: 388000,
    image: 'images/car-ford-f150-raptor.jpg',
    gallery: ['images/car-ford-f150-raptor.jpg', 'images/gallery/bronco-interior.jpg', 'images/gallery/bronco-interior2.jpg'],
    features: ['FOX Live Valve מתלים', 'גלגלים 37"', '5.5 רגל ארגז', 'SYNC 4 12" מסך', 'Pro Power Onboard 2kW', 'מצלמת שטח 360°'],
    history: 'יבוא ישיר · 0 ק"מ'
  },
  {
    id: 'gle-450d',
    name: 'Mercedes GLE 450d',
    nameHe: 'מרצדס GLE 450d',
    eyebrow: 'DIESEL · 2025 · MERCEDES',
    brand: 'Mercedes-Benz', year: 2025, fuel: 'דיזל',
    engine: '3.0L I6 דיזל + EQ Boost', hp: 367, nm: 750, accel: 6.1, topSpeed: 250,
    transmission: '9G-TRONIC', drive: '4MATIC AWD',
    mpg: '12.5 ק"מ/ליטר',
    seats: 5, doors: 5, length: 4924, width: 1947, height: 1772, weight: 2275,
    dealerPrice: 800000, ourPrice: 465000,
    image: 'images/car-mercedes-gle-450d.jpg',
    gallery: ['images/car-mercedes-gle-450d.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-dashboard.jpg', 'images/gallery/g63-showroom.jpg'],
    features: ['MBUX 12.3" כפול', 'AIRMATIC + Active Body', 'גג פנורמי', 'מצלמות 360°', 'תאורת אווירה 64 צבעים', 'Burmester 13 רמקולים'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות יצרן'
  },
  {
    id: 'cybertruck',
    name: 'Tesla Cybertruck AWD',
    nameHe: 'טסלה סייברטראק AWD',
    eyebrow: 'EV · 2025 · TESLA',
    brand: 'Tesla', year: 2025, fuel: 'חשמלי',
    engine: 'Dual Motor חשמלי', hp: 600, nm: 1000, accel: 4.1, topSpeed: 180,
    transmission: 'יחס יחיד', drive: 'AWD חשמלי כפול',
    mpg: '547 ק"מ טווח',
    seats: 6, doors: 4, length: 5683, width: 2200, height: 1791, weight: 3104,
    dealerPrice: 750000, ourPrice: 429000,
    image: 'images/car-tesla-cybertruck-awd.jpg',
    gallery: [
      'images/car-tesla-cybertruck-awd.jpg',
      'images/gallery/cyber-interior.jpg',
      'images/gallery/cyber-screen.jpg',
      'images/gallery/cyber-seat.jpg',
      'images/gallery/tesla-cybertruck-awd-cyber-1.jpg',
      'images/gallery/tesla-cybertruck-awd-cyber-3.jpg'
    ],
    features: ['פלדה Ultra-Hard 30X', 'הגה Steer-by-Wire', 'מסך 18.5" 2200×1300', 'Vault ארגז 1.83 מ׳', '11kW מוצא חשמל', 'AutoPilot'],
    history: 'יבוא ייחודי · 0 ק"מ · אחריות סוללה 8 שנים'
  },
  {
    id: 'bmw-x5',
    name: 'BMW X5 xDrive40i',
    nameHe: 'ב.מ.וו X5 40i',
    eyebrow: 'I6 · 2025 · BMW',
    brand: 'BMW', year: 2025, fuel: 'בנזין',
    engine: '3.0L I6 ביטורבו 48V', hp: 380, nm: 540, accel: 5.4, topSpeed: 250,
    transmission: '8-Speed Steptronic', drive: 'xDrive AWD',
    mpg: '10.8 ק"מ/ליטר',
    seats: 5, doors: 5, length: 4922, width: 2004, height: 1745, weight: 2245,
    dealerPrice: 720000, ourPrice: 435000,
    image: 'images/car-bmw-x5.jpg',
    gallery: ['images/car-bmw-x5.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/g63-dashboard.jpg'],
    features: ['BMW Live Cockpit Pro', 'iDrive 8.5', 'Harman/Kardon 16 רמקולים', 'גלגלים 21"', 'גג פנורמי', 'Sport+ Suspension'],
    history: 'יבוא ישיר · 0 ק"מ'
  },
  {
    id: 'bronco-bigbend',
    name: 'Ford Bronco Big Bend',
    nameHe: 'פורד ברונקו ביג בנד',
    eyebrow: 'I4 · 2025 · FORD',
    brand: 'Ford', year: 2025, fuel: 'בנזין',
    engine: '2.3L I4 EcoBoost ביטורבו', hp: 300, nm: 440, accel: 7.2, topSpeed: 175,
    transmission: '10-Speed Auto', drive: '4WD',
    mpg: '9.0 ק"מ/ליטר',
    seats: 5, doors: 4, length: 4811, width: 1928, height: 1851, weight: 2150,
    dealerPrice: 380000, ourPrice: 226000,
    image: 'images/car-ford-bronco-raptor.jpg',
    gallery: ['images/car-ford-bronco-raptor.jpg', 'images/gallery/bronco-interior.jpg', 'images/gallery/ford-bronco-raptor-bronco-2.jpg', 'images/gallery/ford-bronco-raptor-bronco-4.jpg'],
    features: ['GOAT 7 מצבי שטח', 'גג נשלף', 'דלתות נשלפות', 'SYNC 4 8" מסך', 'Trail Control', 'גלגלים 17"'],
    history: 'יבוא ישיר · 0 ק"מ'
  },
  {
    id: 'mustang-gt',
    name: 'Ford Mustang GT V8',
    nameHe: 'פורד מוסטנג GT V8',
    eyebrow: 'V8 · 2025 · FORD',
    brand: 'Ford', year: 2025, fuel: 'בנזין',
    engine: '5.0L V8 Coyote', hp: 486, nm: 567, accel: 4.2, topSpeed: 250,
    transmission: '10-Speed Auto / 6MT', drive: 'RWD',
    mpg: '8.5 ק"מ/ליטר',
    seats: 4, doors: 2, length: 4811, width: 1916, height: 1402, weight: 1745,
    dealerPrice: 430000, ourPrice: 251000,
    image: 'images/car-mustang-gt-v8.jpg',
    gallery: [
      'images/car-mustang-gt-v8.jpg',
      'images/gallery/mustang-gt-mustang-1.jpg',
      'images/gallery/mustang-gt-mustang-2.jpg',
      'images/gallery/mustang-gt-mustang-3.jpg'
    ],
    features: ['Performance Pack', 'Active Exhaust', 'Recaro מושבי ספורט', 'מסך 13.2" + לוח מחוונים 12.4"', 'Brembo בלמים', 'MagneRide מתלים'],
    history: 'יבוא ישיר · 0 ק"מ'
  },
  {
    id: 'kia-ev9',
    name: 'Kia EV9 RWD',
    nameHe: 'קיה EV9 RWD',
    eyebrow: 'EV · 2025 · KIA',
    brand: 'Kia', year: 2025, fuel: 'חשמלי',
    engine: 'מנוע חשמלי אחורי', hp: 215, nm: 350, accel: 8.2, topSpeed: 185,
    transmission: 'יחס יחיד', drive: 'RWD',
    mpg: '563 ק"מ טווח · WLTP',
    seats: 7, doors: 5, length: 5010, width: 1980, height: 1755, weight: 2470,
    dealerPrice: 510000, ourPrice: 297000,
    image: 'images/car-kia-ev9.jpg',
    gallery: ['images/car-kia-ev9.jpg', 'images/gallery/g63-interior.jpg', 'images/gallery/cyber-seat.jpg'],
    features: ['Triple Display 30"', 'V2L 3.6kW מוצא חשמל', 'Highway Driving Assist 2', 'Meridian 14 רמקולים', '7 מושבים', 'גג זכוכית'],
    history: 'יבוא ישיר · 0 ק"מ · אחריות סוללה 7 שנים'
  },
  {
    id: 'rivian-r1s',
    name: 'Rivian R1S Dual',
    nameHe: 'ריביאן R1S דואל',
    eyebrow: 'EV · 2025 · RIVIAN',
    brand: 'Rivian', year: 2025, fuel: 'חשמלי',
    engine: 'Dual Motor חשמלי', hp: 533, nm: 827, accel: 4.5, topSpeed: 200,
    transmission: 'יחס יחיד', drive: 'AWD חשמלי',
    mpg: '660 ק"מ טווח · EPA',
    seats: 7, doors: 5, length: 5100, width: 2015, height: 1840, weight: 3025,
    dealerPrice: 700000, ourPrice: 408000,
    image: 'images/car-rivian-r1s.jpg',
    gallery: ['images/car-rivian-r1s.jpg', 'images/gallery/cyber-interior.jpg', 'images/gallery/cyber-screen.jpg'],
    features: ['Tank Turn סיבוב במקום', 'Driver+ אוטונומי', 'Meridian 22 רמקולים', 'מתלי אוויר אדפטיביים', 'אגירה Frunk 326L', 'Camp Mode'],
    history: 'יבוא ייחודי · 0 ק"מ'
  },
  {
    id: 'wrangler',
    name: 'Jeep Wrangler Sport',
    nameHe: 'ג׳יפ רנגלר ספורט',
    eyebrow: 'V6 · 2025 · JEEP',
    brand: 'Jeep', year: 2025, fuel: 'בנזין',
    engine: '3.6L V6 Pentastar', hp: 285, nm: 353, accel: 7.5, topSpeed: 180,
    transmission: '8-Speed Auto / 6MT', drive: '4WD Command-Trac',
    mpg: '7.5 ק"מ/ליטר',
    seats: 5, doors: 4, length: 4882, width: 1894, height: 1839, weight: 2020,
    dealerPrice: 400000, ourPrice: 236000,
    image: 'images/car-bmw-x5.jpg',
    gallery: ['images/car-bmw-x5.jpg', 'images/gallery/bronco-interior.jpg'],
    features: ['גג נשלף', 'דלתות נשלפות', 'שמשה מתקפלת', 'Rock-Trac 4:1', 'Trail Rated', 'Uconnect 12.3" מסך'],
    history: 'יבוא ישיר · 0 ק"מ'
  },
  {
    id: 'traverse-z71',
    name: 'Chevy Traverse Z71',
    nameHe: 'שברולט טראוורס Z71',
    eyebrow: 'V6 · 2025 · CHEVROLET',
    brand: 'Chevrolet', year: 2025, fuel: 'בנזין',
    engine: '2.5L Turbo I4', hp: 328, nm: 432, accel: 6.6, topSpeed: 180,
    transmission: '8-Speed Auto', drive: 'AWD',
    mpg: '9.5 ק"מ/ליטר',
    seats: 7, doors: 5, length: 5189, width: 1992, height: 1788, weight: 2110,
    dealerPrice: 420000, ourPrice: 245000,
    image: 'images/car-chevy-tahoe-high-country.jpg',
    gallery: ['images/car-chevy-tahoe-high-country.jpg', 'images/gallery/g63-interior.jpg'],
    features: ['Z71 Off-Road Pack', '17.7" Display', 'Bose Premium', 'גג פנורמי', '7 מושבים', 'Super Cruise אופציה'],
    history: 'יבוא ישיר · 0 ק"מ'
  }
];

// 5 stock-board models with biggest price gaps
const STOCK_MODELS = [
  { id: 'g580eq', name: 'G580 EQ', symbol: 'MBG580', dealer: 1680000, ours: 656000, change: -1024000, pct: -61.0 },
  { id: 'lucid-air', name: 'Lucid Air', symbol: 'LCID·AP', dealer: 800000, ours: 376000, change: -424000, pct: -53.0 },
  { id: 'g63', name: 'G63 AMG', symbol: 'MBG63', dealer: 2100000, ours: 1180000, change: -920000, pct: -43.8 },
  { id: 'bronco-raptor', name: 'Bronco Raptor', symbol: 'FORD·BR', dealer: 800000, ours: 464000, change: -336000, pct: -42.0 },
  { id: 'tesla-x', name: 'Model X LR', symbol: 'TSLA·X', dealer: 800000, ours: 429000, change: -371000, pct: -46.4 }
];

window.CARS = CARS;
window.STOCK_MODELS = STOCK_MODELS;
window.FX = FX;
